### ISSUE TITLE
Generating a static file

### ISSUE THREAD

**Issue by vmarcella** [quicky-dev/generator#1]
## Objective 
Generate a static file that can be deployed on to a users machine to setup their bash profile and environment

## Tasks
- [x] - Research into tools that are generally needed
- [x] - Create a template script that needs to be generated
- [x] - Create generator for the scripts
- [x] - Test the generator and generated script out to ensure that it works
