### ISSUE TITLE
Generating a dynamic setup file

### ISSUE THREAD

**Issue by vmarcella** [quicky-dev/generator#2]
## Objective
Dynamically generating setup files based on input provided by users through the frontend of quicky

## Tasks
- [ ] - Reading in the users input & processing it
- [ ] - Generate the correct output file along with a uuid for the user in case they need another download
- [ ] - determine the best way to save the generated files for backend accessibility
- [ ] - Test both the file generator and generated file to ensure that everything installed correctly and that there were no errors that occurred within generation.
